### ISSUE TITLE
Data race when running test with 1000 goroutines on Travis CI

### ISSUE THREAD

**Issue by philippgille** [allegro/bigcache#110]
I'm developing a key-value store abstraction and implementation / wrapper package for Go and one of the implementations is for BigCache. I have a test that launches 1000 goroutines to concurrently interact with the underlying store. On my local machine it works fine all the time, but on Travis CI I **sometimes** get this warning and then a subsequent error:

```
WARNING: DATA RACE
Write at 0x00c43a932018 by goroutine 163:
  runtime.slicecopy()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/slice.go:192 +0x0
  github.com/allegro/bigcache/queue.(*BytesQueue).push()
      /home/travis/gopath/src/github.com/allegro/bigcache/queue/bytes_queue.go:129 +0x2ca
  github.com/allegro/bigcache/queue.(*BytesQueue).Push()
      /home/travis/gopath/src/github.com/allegro/bigcache/queue/bytes_queue.go:81 +0xf0
  github.com/allegro/bigcache.(*cacheShard).set()
      /home/travis/gopath/src/github.com/allegro/bigcache/shard.go:75 +0x209
  github.com/allegro/bigcache.(*BigCache).Set()
      /home/travis/gopath/src/github.com/allegro/bigcache/bigcache.go:117 +0x153
  github.com/philippgille/gokv/bigcache.Store.Set()
      /home/travis/gopath/src/github.com/philippgille/gokv/bigcache/bigcache.go:42 +0x1e3
  github.com/philippgille/gokv/bigcache.(*Store).Set()
      <autogenerated>:1 +0xa0
  github.com/philippgille/gokv/test.InteractWithStore()
      /home/travis/gopath/src/github.com/philippgille/gokv/test/test.go:306 +0x1d0
```
For the full test output see: https://travis-ci.org/philippgille/gokv/builds/468489707#L1206

The test itself is: https://github.com/philippgille/gokv/blob/e48dea7fdf56ca55fecd32be28d8fd895682ae3a/bigcache/bigcache_test.go#L42
The implementation is: https://github.com/philippgille/gokv/blob/e48dea7fdf56ca55fecd32be28d8fd895682ae3a/bigcache/bigcache.go

Is this an error in the way I use BigCache? Or is this a bug in BigCache itself?

**Comment by cristaloleg** [comment]
Is it reproducible with the latest Go? (1.11.4 already)

**Comment by mxplusb** [comment]
@philippgille can you give an [MCVE](https://stackoverflow.com/help/mcve)? I'm interested to see what's up.

**Comment by moeryomenko** [comment]
@philippgille try set ```Eviction: time.Duration(5 * time.Second)``` into https://github.com/philippgille/gokv/blob/master/bigcache/bigcache_test.go#L177-L179

for `Options` you wrote https://github.com/philippgille/gokv/blob/master/bigcache/bigcache.go#L86-L92, but is not true for https://github.com/allegro/bigcache/blob/master/config.go#L9-L10. 

I apologize for my poor knowledge of English

**Comment by mxplusb** [comment]
@philippgille are you still running into this issue on go1.12? Also, this is specific to TravisCI, yeah?

**Comment by philippgille** [comment]
Thanks for the continued interest in solving this issue. I tried to create an MCVE a while ago but couldn't reproduce the issue with it. And the gokv project wasn't build on Jenkins very often in the recent months, so I can't say whether the issue disappeared by now. I will trigger some builds on the weekend and get back to you.

**Comment by mxplusb** [comment]
Thanks for trying to come up with an MCVE, that will really help. I will leave this open for now on the off chance you see it over the weekend.

**Comment by cristaloleg** [comment]
Kindly ping @philippgille @mxplusb. Any progress/updates?

**Comment by janisz** [comment]
https://github.com/philippgille/gokv/pull/89

**Comment by janisz** [comment]
@cristaloleg I think we can close this issue

**Comment by philippgille** [comment]
Sorry for not being very responsive in this thread last year! And thanks again @janisz for the recent PR! If my Travis CI builds fail with a similar message again some time in the future I will create a new issue and link this one.

Thanks everyone for willing to help solve the issue!
