### ISSUE TITLE
GC pause time

### ISSUE THREAD

**Issue by craftsdong** [allegro/bigcache#125]
the PauseTotal is total pause for all collections, but only once collection. so is there any mistake for calulate freecache and map pause time. 

`fmt.Println("GC pause for freecache: ", gcPause())`
`fmt.Println("GC pause for map: ", gcPause())`

I think there maybe minus

**Comment by mxplusb** [comment]
Sorry, could you clarify your statement? Do you mean we're showing the wrong garbage collection metrics in the benchmarking suite?

**Comment by craftsdong** [comment]
I am confused by the result when I alter the order of comparison. I got the reault as follows:
  
![image](https://user-images.githubusercontent.com/46548619/54107981-b39e2a80-4415-11e9-921d-f5ff029cd0ac.png)

**Comment by janisz** [comment]
I think it was fixed by https://github.com/allegro/bigcache-bench/pull/8
