### ISSUE TITLE
sounds very good but production ready?

### ISSUE THREAD

**Issue by hiqbn** [allegro/bigcache#131]
i think i saw some issues here which makes me wonder if it's ready for production use. is it?

**Comment by cristaloleg** [comment]
Yes, it's production ready for a long time 😉

**Comment by hiqbn** [comment]
the latest commit message doesnt sound very reassuring...
https://github.com/allegro/bigcache/commit/e24eb225f15679bbe54f91bfa7da3b00e59b9768

can someone explain the message and still make sense of being production ready? what should i look out for?

**Comment by mxplusb** [comment]
@hiqbn no piece of software is perfect, and bigcache is no exception. We do our best to ensure there's as little bugs as possible - hence the very comprehensive test suite. Regarding e24eb22, there was a test case pushed in #119 that will let us ensure if we keep seeing it, it'll fail and we'll address it if or when it comes up.

**Comment by hiqbn** [comment]
@mxplusb so it is fixed or still under review?

**Comment by mxplusb** [comment]
@hiqbn to my knowledge it was fixed in February 2019.
