### ISSUE TITLE
possibe to do layeredcache like https://github.com/karlseguin/ccache

### ISSUE THREAD

**Issue by hiqbn** [allegro/bigcache#132]
layered cache for use for http caching like 
https://github.com/karlseguin/ccache

**Comment by cristaloleg** [comment]
Hm...so what do you propose exactly? 🤔

**Comment by hiqbn** [comment]
cache.Set("my-unique-key", "field",[]byte("value"))

entry, _ := cache.Get("my-unique-key","field)

cache.Del("my-unique-key")

**Comment by cristaloleg** [comment]
Forgive me, but I don't get it. 
Basically we've a cache of...caches, am I get you correctly?

**Comment by hiqbn** [comment]
sort of cache of caches, more like redis hash functions hset, hget etc.

**Comment by hiqbn** [comment]
alternatively, how do we achieve the same thing with bigcache?

**Comment by cristaloleg** [comment]
1st solution I see: 
```
<cache_name> + <key> : <value>
```

So basically you've a prefix for each key, which says 'where' this keys is present.

**Comment by hiqbn** [comment]
ok. thx

**Comment by hiqbn** [comment]
key + field = value

i can't clear all key fields with delete(key)
i would like to achieve hset / hget like redis with bigcache. how can i do this?

**Comment by cristaloleg** [comment]
Well, you can, you need to iterate over keys and check their prefix (see https://godoc.org/github.com/allegro/bigcache#BigCache.Iterator).
Yes, this is O(|number of keys|) but still a thing 😉

**Comment by hiqbn** [comment]
that's not very smart. can design one for layeredcache?

**Comment by hiqbn** [comment]
what other options do we have? smart / efficient way pls.

**Comment by cristaloleg** [comment]
I suspect that number of top layers is not very big, and it's also constant (with a high probability).
So making something like `map[string]*bigcache.Bigcache` will not hurt. Care to try?

**Comment by hiqbn** [comment]
sounds like a good idea. will implement when i have the time. i'm checking other options first.
