### ISSUE TITLE
I just made a variant of bigcache, and will add more features.

### ISSUE THREAD

**Issue by hiqinternational** [allegro/bigcache#135]
It's my first time editing on github. bigcache is very useful and definitely worth "improving"
Looking forward to feedback. Thanks for the software.

https://github.com/hiqinternational/bigcache

**Comment by cristaloleg** [comment]
IMO: that's kinda not a pleasant behaviour in open source world. That's sounds harsh.

**Comment by hiqinternational** [comment]
yes, sorry, thanks for the constructive criticism. i'm still learning how to contribute to open source world. guidance appreciated. thx.

**Comment by un000** [comment]
What's the point to maintain another repo? Welcome your commits here.

**Comment by hiqinternational** [comment]
i changed the string to []byte. i dont think bigcache will want that as part of the pull... unless we change it to accept []byte as key with another function... that'll really be quite some work.

**Comment by mxplusb** [comment]
@hiqinternational in open source, it's generally best to start with a question about functionality via a new issue, propose new behaviour with either a another issue or pull request, and then discuss the changes. Forking is acceptable but saying _this software is very useful and definitely worth "improving"_ can be perceived as unkind, especially where communication is strictly text-based, and there's no body language or tonal inflection.

On that note, this issue doesn't contain questions or concerns, so I'm closing as off-topic.
