### ISSUE TITLE
Event handlers for evict?

### ISSUE THREAD

**Issue by pyros2097** [allegro/bigcache#14]
Is it possible to have eviction handler like in the lib https://github.com/bluele/gcache? Because we need to do some cleanup whenever a cache key is evicted.

I checked out your source and it seems you do have some support for it, buts internal only here
https://github.com/allegro/bigcache/blob/master/bigcache.go#L138

**Comment by druminski** [comment]
Hi, indeed, this feature is possible and rather simple, I will prepare it today, please stay in touch 😀

**Comment by druminski** [comment]
@pyros2097 please take a look at #15 and let us know if it solves this issue.

**Comment by pyros2097** [comment]
@druminski Great!That does it! Man you guys are awesome :trophy:  so quick in making this change. Thanks! :smile:

**Comment by pyros2097** [comment]
I guess the readme has to be update with the new  OnRemove func(key string, entry []byte).

**Comment by janisz** [comment]
Good point, @pyros2097 would you like to do it?

**Comment by druminski** [comment]
I've found a minute and created PR #16 which updates readme.md. I decided to set default value (nil) in the example from readme, because when callback is provided then the oldest entries are unwrapped and this is unnecessary operation for clients who don't need OnRemove feature.
