### ISSUE TITLE
Signing commits

### ISSUE THREAD

**Issue by mxplusb** [allegro/bigcache#140]
I appreciate the decision behind wanting each commit to be PGP-signed for verification and security, but it raises the bar for contributors and is difficult to maintain. There are several open PRs (one by me) that can't be merged because they need to be signed. Can the decision to required PGP-signed commits be re-evaluated? It's not a very common practice from what I have seen.

**Comment by janisz** [comment]
@cristaloleg Can we remove this requirements? Or at least allow merging by admins? I have no write access to  repo settings since I no longer work at @allegro

**Comment by cristaloleg** [comment]
Many of other Allegro projects do not require signed commits, so signing is currently disabled.
