### ISSUE TITLE
please update the import path in v2

### ISSUE THREAD

**Issue by gracenoah** [allegro/bigcache#142]
Please see https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

With go modules, you can't simply tag v2.0.0 to release version 2. You should change the import path in order to allow both v1 and v2 to be used at the same time.

**Comment by janisz** [comment]
@cristaloleg Why did we released it as 2.0? There were no breaking changes

**Comment by cristaloleg** [comment]
Yeah, that's what I was looking for

**Comment by cristaloleg** [comment]
Thank you @gracenoah for pointing on an inconsistency 🎉

**Comment by gracenoah** [comment]
Sorry, there's actually one more thing necessary. You have to update the import path used in your own files. Ex:
https://github.com/allegro/bigcache/blob/ca9a59ef2ad95442436b6a0ed9f061e6a47e376a/server/server.go#L11
https://github.com/allegro/bigcache/blob/ca9a59ef2ad95442436b6a0ed9f061e6a47e376a/caches_bench/caches_gc_overhead_comparison.go#L9
etc.

**Comment by cristaloleg** [comment]
Ahhhh...we've `bigcache` imports inside, tricky :D

**Comment by gracenoah** [comment]
After this is fixed I think it's best to release 2.0.1 because re-tagging releases can cause issues with package caches.

**Comment by cristaloleg** [comment]
Yep, good point, `2.1.0` looks fine too

**Comment by viktorwork** [comment]
Any news?

**Comment by savsgio** [comment]
Hi, you could rerelease the version 2.1, because it has an invalid version format of go modules, it must follow the semantic versioning, that is, X.Y.Z (not X.Y).

Thanks

**Comment by cristaloleg** [comment]
@savsgio v2.1.1 https://github.com/allegro/bigcache/releases/tag/v2.1.1

**Comment by savsgio** [comment]
Thanks 👍
