### ISSUE TITLE
How to store the interface{} type

### ISSUE THREAD

**Issue by hjdo** [allegro/bigcache#145]
Thank you for your hard work.
I want to know how to store interface{} data, the Google is not found, I hope to get help.

**Comment by cristaloleg** [comment]
You need to serialise your data to `[]byte`.

One of the examples is JSON or Gob:
```go
// v is your variable of type interface{}
raw, err := json.Marshal(v)
if err != nil {...}

// and `raw` is a []byte which you can save to Bigcache
```

**Comment by hjdo** [comment]
Thank you for your reply, I have already started using it, happy.😁
