### ISSUE TITLE
Farewell

### ISSUE THREAD

**Issue by mxplusb** [allegro/bigcache#146]
Team,

It's been a great couple years working on this project on and off, I've enjoyed it and I'm glad I was able to contribute. I've come to realise I have enough going on in life that I can't feasibly be an active part of this project any more, especially as I write less and less Go these days.

It's time to remove me as a maintainer. :)

Thanks,

mxplusb

**Comment by janisz** [comment]
Thank you for your service, sir

**Comment by cristaloleg** [comment]
Thanks, I hope it wasn't caused by upcoming `try` in Go.
Thanks once more 🎉

**Comment by mxplusb** [comment]
> I hope it wasn't caused by upcoming try in Go.

I'd heard about it, but I haven't looked into it. This was driven purely by my focus having shifted slowly to other things and realising I no longer have the time to focus on this project like I thought I did.

I'll be around, so feel free to tap me for questions, I just can't be a maintainer. :)
