### ISSUE TITLE
Randomized TTL on items

### ISSUE THREAD

**Issue by durandj** [allegro/bigcache#149]
I saw that #81 and #13 both referenced having a TTL on each item. Both were closed because no one wanted to make a PR or no one wanted to break the existing API. My team at work is looking to add randomized TTL's to our service so that if items are added to the cache in bulk, they don't all expire at once. I could see two different ways this could be implemented in `bigcache`. Either a new handler can be added of the form `func (c *BigCache) SetItemWithTTL(key string, entry []byte, ttl time.Duration) error` or a new config option could be added called `RandomOffset time.Duration` that defines by how much the TTL can be offset when a new key is added with `SetItem`.

If I were to create a PR, do you have a preference on which API would be preferred? I'm leaning more towards the config option and having the library figure out how much to randomize the offset since it makes the logic on the consumer side simpler **and** is still backwards compatible by defaulting to an offset of `0`.

This is admittedly more a specific solution to the problem so if you would prefer adding `SetItemWithTTL` instead to be more general purpose, I can do that instead :)

**Comment by cristaloleg** [comment]
Hi, I'm not sure that `RandomOffset` property will be suitable for everyone. Setting object with a specific TTL sounds more reasonable.

This idea doesn't look like a harmful change, PR sounds welcome :)

Thanks you for an interesting case.

**Comment by durandj** [comment]
My team and I spent a good amount of time trying to figure out how to make this work **without** hurting performance. Given that we're not the first to want per item TTL's and I'm sure we're not going to be the last, I figured it would be a good idea to spend some time documenting what we looked at and why we didn't end up implementing this.

**What we use the cache for now:**

We run a service that provides querying of data at very low latencies to other services. This service is primarily composed of two relevant components: a sidecar attached other other services and a service for storing large amounts of data. The storage service has an API for querying data and this service responds relatively quickly but we don't want to hit this service too often. The sidecar knows how to talk to the storage service and also has a built-in cache that it can consult before hitting the storage service.

**What problem we want to solve:**

Overall this architecture works really well and we are able to get very quick response times to the service that consumes our data. The problem comes in when the consuming service does background jobs that require lots of data on regular intervals. These background tasks basically propagate the entire cache because of how much they query for. By the time the next background task starts, the cache has expired and repopulates again causing significant load on our backend service. We don't have control over how often these background tasks happen and we let the consumer determine the cache expiry time and the max size of the cache (that way they can properly determine the resources they need). This is problematic for us though since it keeps our backend service scaled artificially high (when it starts scaling down the consumer then hits us again and we scale back up).

We only have so much control over how this particular consumer operates and we're working with them to address these issues from their end, they're not our only consumer and we expect these issues to happen with ours so we wanted to solve it more on our end.

**What solutions we came up with:**

After digging more into the internals of how `bigcache` works we came up with two possible solutions to the problem.

The first is to try and keep the ordering of the data in the cache the way it is now. So the oldest thing in the cache is at the beginning of the ring buffer. This has the nice benefit of making the cache expiry logic really easy. Unfortunately it makes writes/updates really hard since you need to reorder the cache every time you write to it. So say you have two items in the cache already and they're contiguous, when you try to write the third and it happens to expire between the two items, you need to make space between the two items and insert the new item into the cache. To do this kind of insertion either means allocation of a new ring buffer and copying all the existing data and the new data into the new buffer or shifting everything in the existing buffer to make room. You also have to update all the indices that point to an item in the buffer. This is a potentially long operation that you would need to lock on the entire time. It also means a lot of potential memory churn.

The other strategy we considered was to just not rely on buffer order any more and continue doing writes at the end of the buffer. This makes writing easier and reading stays the same, however cleanup of expired items is now more complicated. If you have to expire something in the middle, you have to now reclaim that space at some point or you end up with fragmentation of your buffer. You could eat this cost at periodic writes if you wanted to but that means a slower write time that could take an undefined amount of time. Or you could have a second goroutine that does the cleanup but when the defragmentation is happening you can't read or write to the cache.

Both options have pretty significant performance impacts that would really hurt the performance of the cache. While it would be incredibly nice to have this kind of flexibility on the expiry times, it didn't feel worth it given how much of a hit we would take on read/write times.

**What we did instead:**

Since we couldn't modify the cache we ended up modifying how we use the cache. Since we don't want all of the instances of our sidecar having their cache expire at roughly the same time, we decided to add a bit of random variation into the configured expiry time for each sidecar instance. So we might have one sidecar with an expiry time of 5 minutes per item and another that has an expiry of 7 minutes. It's still too soon for us to know how much of an impact this will have but we're hoping that it will be a simpler solution to the problem and work well enough.

Hopefully this will help anyone else trying to do something similar.

**Comment by mxplusb** [comment]
Thanks for the write-up @durandj, it helps!

> Both options have pretty significant performance impacts that would really hurt the performance of the cache.

Your cache implementation or bigcache?

**Comment by durandj** [comment]
Hurt the performance of `bigcache` at large.

**Comment by mxplusb** [comment]
Would you be able to provide some input on how that impacted the performance of bigcache? It would be really helpful.

**Comment by durandj** [comment]
We didn't implement either solution so I don't have hard numbers on what the actual impact would be but I can talk a bit more about each solution and where we saw strong potential for slow downs.

In the solution where we try and maintain the order of the ring buffer (so the item at the head of the buffer is the oldest and the item at the tail is the newest), you would need to add sorting to each write to keep that ordering. That means keeping track of the exact TTL for each item (which would be needed regardless) and then using these TTL records to reorder the buffer whenever a new item needs to be inserted somewhere in the middle. It wouldn't be hard or expensive to do a binary search to find the correct place to put the new item, it would be difficult to shift things around to make room. If the cache has few items in it that are relatively small in size, then shifting is easy and won't be bad. But if you need to shift a lot of items or you have items that are pretty large, moving them because much more time consuming. That of course makes the assumption that you're writing inline to the buffer. You could alternatively create a new ring buffer, populate that with the old and new data and replace the old buffer but that means copying everything every time which could cause some memory churn or could mean running out of memory since you're doubling the memory usage for that shard.

I suppose you could sort of get around this by keeping the number of shards per cache higher and therefore keep the number of items per shard low but this feels like it relies more on everything going perfectly. What I mean is that you're relying on everything hashing very evenly and assuming that the shard count to expected number of items/item size all balances out well. Ideally a consumer of `bigcache` will correctly tune the cache for their needs, I wouldn't want to expect this to be the case in all situations.

In the other solution we considered we looked at getting rid of the ordering on the ring buffer. You no longer rely on the head being the oldest but instead just iterate over the cache to find the oldest item whenever you need to do an eviction. This already makes evicting more expensive and depending on the workload, that might not be a great tradeoff. The other big issue we found with this approach is that the buffer is going to get heavily fragmented as items are removed throughout it. You might end up with these pockets of no longer used memory that need to be reclaimed at some point. You could do this after each eviction or each round of evictions but that means blocking all writes to the cache for a potentially long period of time (the cache could have gigabytes of data with 1000's or more items). You could also try and not do any cleanup and just insert new items in empty slots but that could mean much less efficient use of memory if you end up with many pockets of memory that are too small to be useful for new items. You also need to start tracking the unused memory which means now doing memory management which is difficult and means more memory usage.

**Comment by mxplusb** [comment]
> The other big issue we found with this approach is that the buffer is going to get heavily fragmented as items are removed throughout it. You might end up with these pockets of no longer used memory that need to be reclaimed at some point.

To make sure I understand correctly, you are suggesting that by iterating and updating the oldest item, there's a chance for memory segments to be non-contiguous, leaving essentially empty memory segments that can't be assigned? Is that an accurate understanding of what you are suggesting?

**Comment by durandj** [comment]
Right so say you have 5 items in the buffer and they're in some random order. If you remove the oldest item, it might be somewhere in the middle. So you now have an empty slot that is available. Let's then say that two new items are added to the buffer and they are able to fill most of the space that that previous item occupied. There might now be an area of the buffer that is too small to be usable for new items.

You could have this all over the buffer and could try and join those free slots together to maybe make something big enough for a new item but that requires some additional work.
