### ISSUE TITLE
Confused with LifeWindow and CleanWindow

### ISSUE THREAD

**Issue by AnikHasibul** [allegro/bigcache#152]
There's already a closed issue #138 . But I'm still confused.

Can someone please explain:

* What is `LifeWindow`?
* When does `LifeWindow` starts counting?
* What is `CleanWindow`?
* When does `CleanWindow` starts count?
* Is `LifeWindow` and `CleanWindow` is for each item or all the items?

Thank you!

**Comment by janisz** [comment]
>     * What is `LifeWindow`?
https://github.com/allegro/bigcache/blob/c00e2be7ad487b8fe06fc1da3d62edd19fb54519/config.go#L9-L10
>     * When does `LifeWindow` starts counting?
`LifeWindow` is used when clenup is performed or there is no more space left and new item is going to be inserted.
>     * What is `CleanWindow`?
https://github.com/allegro/bigcache/blob/c00e2be7ad487b8fe06fc1da3d62edd19fb54519/config.go#L11-L13
>     * When does `CleanWindow` starts count?
Think about it as a garbage collector with a schedule. It works in given interval removing items that are stale (exceed it's life window).
>     * Is `LifeWindow` and `CleanWindow` is for each item or all the items?
It's for all the items

**Comment by cristaloleg** [comment]
Yes, you are right @AnikHasibul

**Comment by AnikHasibul** [comment]
> 
>     1. `LifeWindow` is a time. After that time, an entry can be called dead but not deleted.
> 
>     2. `CleanWindow` is a time. After that time, all the dead entries will be deleted, but not the entries that still have life.
> 



Can you please add this to README just for making it clear? I have seen many people had opened issue and confused with this.

**Comment by cristaloleg** [comment]
Sounds reasonable, btw everything is in the documentation 😉 (I mean godoc)

**Comment by AnikHasibul** [comment]
Thank you @cristaloleg and @janisz ! Closing...
