### ISSUE TITLE
package github.com/allegro/bigcache/v2/queue: cannot find package 

### ISSUE THREAD

**Issue by donomii** [allegro/bigcache#156]
Directory v2 does not exist.  patch dc3aaab9 breaks all installs

package github.com/allegro/bigcache/v2/queue: cannot find package "github.com/allegro/bigcache/v2/queue" in any of:
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/github.com/allegro/bigcache/v2/queue (from $GOROOT)
	/home/travis/gopath/src/github.com/allegro/bigcache/v2/queue (from $GOPATH)

**Comment by cristaloleg** [comment]
What version of Go do you use?

**Comment by donomii** [comment]
I was using 1.7 on Travis.  It seems to work with 1.11.

Might be worth a mention in the docs somewhere? From my point of view, it just stopped working

**Comment by cristaloleg** [comment]
As expected, it doesn't work with old Go due to migration to Go modules.

Yep, good point to mention Go compatibility, thanks.
