### ISSUE TITLE
Implement new append function to use bigcache as index for internal database

### ISSUE THREAD

**Issue by snacker81** [allegro/bigcache#158]
Hi there,

I want to use bigcache for an index for my own "memory database".

My records have various fields and are indexed by a uint64 primary key. I now want to add secondary indices for columns pointing to primary keys. The data structure would look like the following:

bigcache[<columnvalue>] = `<uint64>,<uint64>,<uint64>`...

So for example my record has a column "city" and I want to an index on this column:

bigcache_city_index[newyork] = `<pk1>,<pk2>,<pk3>`...

From my point of view this cannot be done today because I will have a race condition between get() and set() calls. 

Right now I am thinking about the following:

- Implement new "AppendUint64(key, id)"
- Look up shard by key
- Lock shard
- Get value
- Add new id (uint64) to value (binary.PutUvarint())
- Set value
- Unlock shard

What are your thoughts about this?

Thank you,
Stefan

**Comment by cristaloleg** [comment]
Hi, your idea look reasonable. bigcache is a key-value store, so to implement locking per index/column you need to lock whole cache(to be precisely - only 1 shard).

I suggest to look into Cockroachdb internals, 'cause they're doing almost the same except the storage layer is based on RocksDB. A bunch of code but you might find something interesting for you 😉
