### ISSUE TITLE
reset key 

### ISSUE THREAD

**Issue by zuzuviewer** [allegro/bigcache#161]
I have a problem:
      ` cache, _ := bigcache.NewBigCache(bigcache.DefaultConfig(10 * time.Minute))

	cache.Set("my-unique-key", []byte("value"))

	entry, _ := cache.Get("my-unique-key")
	fmt.Println(string(entry))
	cache.Set("my-unique-key", []byte("values"))

	entry, _ = cache.Get("my-unique-key")
	fmt.Println(string(entry))`
set the same key twice with different value.bigcache can get the newer value ,but I don't find any code to delete old value.Did the older value is still in memory,but never couldn't get by user,or delete it already but I didn't seek out

**Comment by zuzuviewer** [comment]
> If an existing key is written to again, it is overwritten by the value of the new key.

@mxplusb ,I don't think so,I didn't see any code to reset array's data with the same key.If it is overwritten the old value,it should change the indexs with stored data after overwritten.I think it is not overwritten old value,it's just append new value and refresh entries with new index.

**Comment by janisz** [comment]
@zuzuviewer You are right, bigcache architecture is based on big queue. We do not remove entries from the middle of it.
