### ISSUE TITLE
Confusing "GC pause time" section

### ISSUE THREAD

**Issue by FrankReh** [allegro/bigcache#163]
The README.md, line 135, still says the GC pause for map is over 10 seconds but the table shows only 52 ms. This discrepancy probably came from #69. Perhaps this line in the README should say the pause used to be over 10 seconds?

The go GC certainly has gone through huge strides since go1.6 so GC pause times might not be a good measure of bigcache's worth any longer. The GC might still be spending precious cycles marking allocated heap memory, but that isn't evident in the pause time.

**Comment by janisz** [comment]
I think we somehow missed this PR in master branch https://github.com/mxplusb/bigcache/commit/1dc8897498212e7bb27c747a04ef9c7dca5c4ab7

**Comment by janisz** [comment]
https://github.com/allegro/bigcache/pull/165
