### ISSUE TITLE
gc pause time on README.MD, which is wrong

### ISSUE THREAD

**Issue by clover-xj** [allegro/bigcache#170]
GC pause time

go version
go version go1.13 linux/amd64

cd caches_bench; go run caches_gc_overhead_comparison.go

Number of entries:  20000000
GC pause for bigcache:  1.506077ms

go version
go version go1.13 linux/arm64

cd caches_bench; go run caches_gc_overhead_comparison.go
Number of entries:  20000000
GC pause for bigcache:  22.382827ms

Number of entries: both  20000000, which is wrong?

**Comment by janisz** [comment]
Can you elaborate?
I run benchmark on my local machine and and ARM server, that's why we get different results for the same test.

**Comment by janisz** [comment]
Can we close it cc @cristaloleg
