### ISSUE TITLE
BigCache took up all the memory(24gb) and was killed by the OS

### ISSUE THREAD

**Issue by gomonuk** [allegro/bigcache#171]
Hi.
I try load to BigCache 200 millions pair key:value, but unfortunately my golang script took up all the memory(24gb) and was killed by the OS. 

My bigcache config: 
`	
config = bigcache.Config{
		Shards:           512,
		LifeWindow:       10 * time.Minute,
		MaxEntrySize:     16,
		HardMaxCacheSize: 0,
	}`

Please tell me what am I doing wrong, maybe I did the wrong config? 
Or can you tell me another solution for this problem?

My golang script:
https://github.com/gomonuk/200kkCache/blob/master/main.go

**Comment by cristaloleg** [comment]
Hi, what is the size of data from CSV ? (24gb / 200M = 120bytes on average)
Have you tried to insert less entries, like 100M ?

**Comment by RaymondKYLiu** [comment]
Hi, I have the same problem in high memory usage.  

As @gomonuk 's sample code, the size of CSV is about 7.7GB (MD5 32Byte*200M + # of 1-200M digits), and BigCache took 24GB memory

I also have experiment with v2.2.1 default configuration. 
The table shows some different size of CSV key-value file are loaded into BigCache

 CSV size | BigCache memory usage  
---------| -------------------------
| 149MB |  750MB
| 139MB |  1.0GB
| 268MB | 1.0GB
| 2.3GB | 9.2GB 

I would like to know how to tune the parameter to decrease memory usage.

Thanks for your great tool.

**Comment by cristaloleg** [comment]
@RaymondKYLiu the simplest optimisation was to store values not as a text, but as bytes (`int` is just 4 bytes), but I haven't received an answer from OP then.

**Comment by cristaloleg** [comment]
Feel free to renew the discussion here.
