### ISSUE TITLE
Improve changelogs

### ISSUE THREAD

**Issue by cristaloleg** [allegro/bigcache#174]
Currently there is no automation for release notes/changelog (see latest https://github.com/allegro/bigcache/releases/tag/v2.1.1 and https://github.com/allegro/bigcache/releases/tag/v1.2.0).

It will be good to have some automation for this, so changelog will be created automatically (it's fine to paste it manually, but the text should be done automatically).

PLEASE if you're going to start working on this issue, comment below, to discuss the solution, thanks in advance.

**Comment by muzavan** [comment]
Hmm, what do you think the best way to generate the Changelog? Commit message?

**Comment by cristaloleg** [comment]
@muzavan I think it will be better to add descriptions at Github releases page (see links in issue description). There should be automatic tools for that.

**Comment by mxplusb** [comment]
@cristaloleg this is what I was using to generate release information: https://github.com/github-changelog-generator/github-changelog-generator

**Comment by cristaloleg** [comment]
@mxplusb can we automate this somehow? even makefile command will be enough, imo

**Comment by mxplusb** [comment]
Yeah, we definitely can. It's mostly around just automating against tag management, so it's pretty straightfoward.

**Comment by gnomeria** [comment]
I've implemented a github action using https://github.com/marketplace/actions/release-drafter.
It will create a release draft every time a pr is merged into the master branch. I can make a pr for this one if you'd like. I think this doesn't interfere with #175 integration tests.

**Comment by cristaloleg** [comment]
@gnomeria sounds awesome, let's make it! +1 🎉

**Comment by gnomeria** [comment]
![image](https://user-images.githubusercontent.com/3047437/66257846-2adb4780-e7c8-11e9-80ba-ed407200f1a8.png)
would be something like this

**Comment by cristaloleg** [comment]
Good, exactly what good project should have.
Sadly current release will be huge, time to change this.
I'm completely for such change with automatic changelog, hopefully no one objections from others @muzavan @janisz
