### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by cristaloleg** [allegro/bigcache#175]
Migrations should be quite easy, it should be enough to reimplement same steps in travis.yml to Github Actions config.

PLEASE if you're going to start working on this issue, comment below, to discuss the solution, thanks in advance.

**Comment by gnomeria** [comment]
Hello, I'm interested on this issue. Can I do it? I'll start by reimplement from the travis.yml

**Comment by cristaloleg** [comment]
@gnomeria yep, good luck

**Comment by gnomeria** [comment]
I was having an issue with uploading the cover results to the coverall using goverall. Do you think we could switch to Codedov @cristaloleg ?

**Comment by cristaloleg** [comment]
@gnomeria yeah, coverall returns 5xx last weeks as I see (other projects too). I'll make an issue regarding migration (let's make it in separate PRs, please)

**Comment by cristaloleg** [comment]
Fixed in #180
