### ISSUE TITLE
Migrate to Codecov

### ISSUE THREAD

**Issue by cristaloleg** [allegro/bigcache#176]
As it was mentioned by @gnomeria in https://github.com/allegro/bigcache/issues/175#issuecomment-538645147 we're interested in migration to an other code coverage service.

**Comment by gnomeria** [comment]
I've implemented initial codecov, but it needs the #175. Also it would need you to set a secret `CODECOV_TOKEN` in the repository so that it could upload the test results.

**Comment by cristaloleg** [comment]
Fixed in #179
