### ISSUE TITLE
Can entry be an interface{} type?

### ISSUE THREAD

**Issue by lcken** [allegro/bigcache#195]
I don't understand why entry should be a []byte type? This makes me do extra Marshal/Unmarshal work when I Set/Get items.

**Comment by cristaloleg** [comment]
Hi there, well, that's one of initial designs goals - be able to cache data received through network. That's why the data is marshaled to []byte. 

You might want to use https://github.com/hashicorp/golang-lru

**Comment by lcken** [comment]
Thanks answering my confusion. I think i would want to use like  [https://github.com/hashicorp/golang-lru](https://github.com/hashicorp/golang-lru) + [https://github.com/patrickmn/go-cache/issues](https://github.com/patrickmn/go-cache/issues).
