### ISSUE TITLE
Empty blob in bytes_queue?

### ISSUE THREAD

**Issue by neal-zhu** [allegro/bigcache#206]
Hi there,
I wonder where does this come from?
```go
const minimumEmptyBlobSize =  32 + headerEntrySize
```
I understand empty blob is used to fill the unused space between head and tail when the queue is re-allocated. But where does 32 come from? 
I change it to 0 and tests still work fine.

PS: this is not a bug, but I don't know how to erase the label

**Comment by janisz** [comment]
It was added in https://github.com/allegro/bigcache/commit/9208dbcc1a2fec6a2e754d25d68f3a8155853e5c with a test for additional allocation. We migght do some changes so 32 is obsolete now. I do not remember why 32 was chosen :(

**Comment by neal-zhu** [comment]
So maybe we can replace it with 0 and we can save some space?  
BTW: have you ever considered storing length in varint way?

**Comment by janisz** [comment]
I agree we should set it to 0 but first I'd like to do some archeology and figure out why we have 32 there.

I like the idea of varint format I think we need to benchmark it
