### ISSUE TITLE
How to store the pointer ??

### ISSUE THREAD

**Issue by zxbfeng** [allegro/bigcache#209]
The bigcache interface :Set（key string, value []byte） ,the value I want to store is a pointer ? so how to do it ?

**Comment by cristaloleg** [comment]
BigCache is about storing serialised (`[]byte`) values.
Well, you can convert data under your pointer to the byte-slice via some serialisation (json, gob, protobuf, etc).

**Comment by zxbfeng** [comment]
ok，thank you! Sorry, please change the Lable to 'question'.The platform automatically Labeled it 'Bug'!

**Comment by mxplusb** [comment]
@zxbfeng it's a GC optimization at the end of the day, our README covers this a bit. :)
