### ISSUE TITLE
What is the purpose of "entries     queue.BytesQueue"

### ISSUE THREAD

**Issue by claygod** [allegro/bigcache#21]
Hi!

Tell us, what it uses "queue"?

**Comment by janisz** [comment]
Hi

Queue is responsible for storing binary objects. Every time you store something (key,value) in bigcache value is saved in queue and index to first byte is stored in map. We are using this approach to minimize GC impact on map. When map contains pointers (e.g, stings, slices or regular pointers) GC will scan whole map. To prevent this we have map of int→int and (half)manually manage memory for maps entries.

Queue is implemented as a byte slice. It grows until reach specified size. When it can't grow more it will delete first added elements to make space for new entry. Probably name queue could be misleading. We adds items at the bottom, removes from top but allow random access.

**Comment by junhsieh** [comment]
Hi @janisz , I am trying to figure it out how the queue.BytesQueue.array works.

I understood that q.head will be reset to leftMarginIndex in the Pop() function once the queue reached the maximum limit. However, what I do not understand is. Let's say:

First cycle:

Entry #1 takes 10 bytes. Entry #2 takes 30 bytes.  Entry #3 takes 30 bytes.

Second cycle (when the queue reached the maximum limit):

Entry #1 takes 20 bytes.

My question is, how do you make sure the Entry #1 in the second cycle will not overlap the existing data in the byte slice?

Thanks
