### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by btesanovic** [allegro/bigcache#23]
Hay there will it be possible to add clear cache method
Thanks

**Comment by janisz** [comment]
I think we can add this method. But how it should works in details. I assume after calling `Clear()` we should end up with no entries in cache. Questions we need to answer

1. Are we going to call [`OnRemove` callback](https://github.com/allegro/bigcache/blob/master/config.go#L27) for every element in cache
2. Are we going to create new (small) shard queues or just use existing one

In my opinion clear should just delete all entries in maps by creating new map (GC will do the rest) and reset indexes in queue (`tail`, `head`, `rightMargin`, `count`). `OnRemove` should NOT be called.

@btesanovic @wendigo What do you think?

**Comment by wendigo** [comment]
@janisz: ```onRemove``` does not make any sense I guess (if you need keys - use iterator before clear()). I agree with you on creating new map and reseting indexes

**Comment by wendigo** [comment]
I'll try to come up with an implementation

**Comment by wendigo** [comment]
Solved @btesanovic. Let me know if it works for you!

**Comment by btesanovic** [comment]
Hey @wendigo  , thanks so much for fast response, this is perfect !!
