### ISSUE TITLE
[Feature Request] Expiration or TTL for each key individually

### ISSUE THREAD

**Issue by RajdeepSardar** [allegro/bigcache#231]
Requesting for adding customized TTL for each key individually. If no TTL is specified, the key can have default TTL.

The interface can be 
```
cache.Set("my-unique-key", []byte("value"), TTL)
```

thanks!

**Comment by janisz** [comment]
The problem with TTL per entry is how we keep entries internally. I think this could be easily achieved with decorator that will add TTL information to entry and during read it will check if entry expired. I prefer to not implement it in bigcache.

**Comment by mxplusb** [comment]
I would agree with @janisz thoughts on this.

**Comment by RajdeepSardar** [comment]
@janisz ,

do you suggest that I put an entry something like
`cache.Set("my-unique-key", []byte("value__TTL"))`
When we do a get, we parse the value, extract the `TTL` and validate whether `TTL` has expired or not.

**Comment by janisz** [comment]
I was thinking about something like this

```
const timeBinaryRepresentationLen = 14

type MyCache struct {
	cache *bigcache.BigCache
}

func (c *MyCache) Set(key string, value byte, TTL time.Duration) error {
    bestBefore := time.Now().Add(TTL)
	timeBinary, err := bestBefore.MarshalBinary()
	if err != nil {
		return err
	}
    v := append(timeBinary, value)
    return c.cache.Set(key, v)
}

func (c *MyCache) Get(key string) ([]byte, error)  {
	value, err := c.cache.Get(key)
	if err != nil {
		return nil, err
	}
	var bestBefore time.Time
	err = bestBefore.UnmarshalBinary(value[:timeBinaryRepresentationLen])
	if err != nil {
		return nil, err
	}
	if time.Now().After(bestBefore) {
		return nil, bigcache.ErrEntryIsDead
	}
	return value, nil
}
```

**Comment by RajdeepSardar** [comment]
Thank you all for the idea and help. It works very well. closing this issue.
