### ISSUE TITLE
support mocking clock in other projects

### ISSUE THREAD

**Issue by flisky** [allegro/bigcache#241]
I'm doing unit testing, and I cannot find a way to mock `Bigcache#clock`.

* the `Bigcache#clock` attribute is unexported
* the `newBigcache(...)` is unexported
* the methods in `clock interface` is unexported, and the [reflect#implements](https://github.com/golang/go/blob/dfdc3880b01d46d1d8125ab9eea0606b2fa5b819/src/reflect/type.go#L1501) rejects due to difference packages. 

I proposal that we export `clock#Epoch`, and it seems have no side effects.

Any suggestions? I'm glad to contribute a patch for this.

**Comment by mxplusb** [comment]
I'm fine with exporting the interface, but I would prefer to leave the rest unexported.
