### ISSUE TITLE
BigCache中Hash冲突的问题

### ISSUE THREAD

**Issue by BoBoGithub** [allegro/bigcache#275]
Hi, 我发现BigCache中未解决Hash冲突的问题，请问有计划补充这部分的实现嘛?

设置缓存代码块：
![image](https://user-images.githubusercontent.com/4011103/112301902-66781300-8cd5-11eb-80af-e8198fe3e44e.png)

获取缓存代码块：
![image](https://user-images.githubusercontent.com/4011103/112302006-84457800-8cd5-11eb-8e3e-1b2135ae50f4.png)

**Comment by janisz** [comment]
I think we will not solve this issue. This is just a cache with no guarantees about data to be available. Collision may happen so we inform user about this.

How would you like to solve it?

**Comment by BoBoGithub** [comment]
> I think we will not solve this issue. This is just a cache with no guarantees about data to be available. Collision may happen so we inform user about this.
> 
> How would you like to solve it?

嗯嗯，知道了．

若要解决的话，我想可以改造cacheShard.HashMap 支持同一个hash对应多个BytesQueue的Index．

**Comment by janisz** [comment]
So instead of `map[int]int` use `map[int][]int`. Original design was optimized for speed. Map of `int`s is not scanned by GC. If we have a slice there then GC will scan it and performance will be degraded.

**Comment by BoBoGithub** [comment]
> So instead of `map[int]int` use `map[int][]int`. Original design was optimized for speed. Map of `int`s is not scanned by GC. If we have a slice there then GC will scan it and performance will be degraded.

`map[int][]int`  这样确实是会影响到GC遍历时的性能，使用FNV生成的Hash 冲突出现机率很小，考虑到高性能确实不值得兼容Hash冲突．

鱼和熊掌不可得兼也．

**Comment by changmu** [comment]
> > So instead of `map[int]int` use `map[int][]int`. Original design was optimized for speed. Map of `int`s is not scanned by GC. If we have a slice there then GC will scan it and performance will be degraded.
> 
> `map[int][]int` 这样确实是会影响到GC遍历时的性能，使用FNV生成的Hash 冲突出现机率很小，考虑到高性能确实不值得兼容Hash冲突．
> 
> 鱼和熊掌不可得兼也．

本来说中文老外都很难懂的，怕是得用翻译软件，你还搞个文言文，xswl

**Comment by BoBoGithub** [comment]
> > > So instead of `map[int]int` use `map[int][]int`. Original design was optimized for speed. Map of `int`s is not scanned by GC. If we have a slice there then GC will scan it and performance will be degraded.
> > 
> > 
> > `map[int][]int` 这样确实是会影响到GC遍历时的性能，使用FNV生成的Hash 冲突出现机率很小，考虑到高性能确实不值得兼容Hash冲突．
> > 鱼和熊掌不可得兼也．
> 
> 本来说中文老外都很难懂的，怕是得用翻译软件，你还搞个文言文，xswl

从老外的回复看，他是看懂了

**Comment by elvin-zheng** [comment]
> > > So instead of `map[int]int` use `map[int][]int`. Original design was optimized for speed. Map of `int`s is not scanned by GC. If we have a slice there then GC will scan it and performance will be degraded.
> > 
> > 
> > `map[int][]int` 这样确实是会影响到GC遍历时的性能，使用FNV生成的Hash 冲突出现机率很小，考虑到高性能确实不值得兼容Hash冲突．
> > 鱼和熊掌不可得兼也．
> 
> 本来说中文老外都很难懂的，怕是得用翻译软件，你还搞个文言文，xswl

what is "老外"?
