### ISSUE TITLE
All bigcache.{Set\Get} is blocked while acquiring RWLock.

### ISSUE THREAD

**Issue by Hank00AAA** [allegro/bigcache#296]
**What is the issue you are having?**
I find my program have goroutine leak, due to bigcache's shard RWLock. 

**What is BigCache doing that it shouldn't?**
All BigCache operation(Get/Set) is blocked, and never recover. 

**Minimal, Complete, and Verifiable Example**
github.com/allegro/bigcache/v3 v3.0.0

My source code is not able to show in github due to my company strategy. But I can support the goroutine pprof to show you guys the problem.  Just like the following. Could you help me to solve the problem? I have no idea to fix or repeat the problem, beacuse it is probability event, it occur in only 10% of my k8s pods.

<img width="876" alt="企业微信20211107-150258@2x" src="https://user-images.githubusercontent.com/32003283/140635750-94e466a5-97df-4422-b31e-4836bcc4ab8a.png">

**Environment:**

- Version (git sha or release):
- OS (e.g. from `/etc/os-release` or winver.exe):
linux 
- go version: 
go 1.14

[pprof.quick_start_banner.goroutine.003.pb.gz](https://github.com/allegro/bigcache/files/7491872/pprof.quick_start_banner.goroutine.003.pb.gz)

**Comment by q337881648** [comment]
![image](https://user-images.githubusercontent.com/22782870/143516721-51fda340-6a15-42ae-889f-05d9beae550d.png)
I also have this problem.
How did you solve it?

**Comment by janisz** [comment]
@q337881648 Can you share minimal reproducible example to replicate this?
