### ISSUE TITLE
Old entries (un-updated) values stored in the byte queue

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [allegro/bigcache#30]
Hello,

Unless I am misunderstanding, when you remove (or evict) an entry to free up space - past instructions can still exist in that queue. That means the following:

SET:
- ABC = 1
- EDF = 1
- ABC = 2

EVICT:
- ABC
- EDF

ABC still exists (due to removing only a single occurrence of it in the queue) On an update should we not be overwriting a keys previous value even in the byte allocation? Otherwise an evict has to run X number of times for X number of changes to the same key name to actually evict the key.

**Comment by janisz** [comment]
Update does overwrite a key. Take a look at [update test]( https://github.com/allegro/bigcache/blob/master/bigcache_test.go#L184). It does it by overriding previous entry with zeroes and storing offset of the new entry. Only the oldest entries are removed.

**Comment by Ewan-GrandSlam** [comment]
Taken I wanted to use the same byte size for all keys (e.g only numbers) wouldn't it be more efficient to overwrite the space with the new value? 

E.g set a flag for a specific key type and all keys represent that byte size. 

If you do not agree with such I will just alter it for my own use otherwise I could add this and add it as a PR

**Comment by janisz** [comment]
Yes and no. If you will never delete entries then indeed this will be better. But we delete oldest data first and updating data will break assumption of keeping newest data at the end of the queue. Updating data in random places of the queue will result with gaps and fragmentation after deleting oldest entries.

When you know size of your entries you can make aggressive optimisations. Definitely flag that enable this optimisations will be welcome.
