### ISSUE TITLE
[Question] Why does evicting during the write helps?

### ISSUE THREAD

**Issue by alok87** [allegro/bigcache#304]
"Eviction is performed during writes to the cache since the lock is already acquired."

Does not it slows down your writes? Did you benchmark this?

**Comment by janisz** [comment]
We decided to evict on write because in cache  reads happen much more often then writes.

Benchmarks are here https://github.com/allegro/bigcache-bench

**Comment by alok87** [comment]
Why not run a separate routine to evict instead(may be a channel communication from the write function to it). Why do it in the write function in a synchronus way?

**Comment by janisz** [comment]
We have a goroutine. Unfortunately it's not set to be controlled externally (which I think is a good idea) but with a local ticker.

https://github.com/allegro/bigcache/blob/77bbae442c22ec7ba79f77cabd56d0e5a9366109/bigcache.go#L91-L104

I think you are referring to this code 
https://github.com/allegro/bigcache/blob/77bbae442c22ec7ba79f77cabd56d0e5a9366109/shard.go#L133-L135
this may be the leftover from the initial super simple design and our internal system. I think it could be deleted as with space limit we will evict old entries anyway.

**Comment by alok87** [comment]
thanks
