### ISSUE TITLE
Eviction not perform after timeout

### ISSUE THREAD

**Issue by gangbanlau** [allegro/bigcache#31]
I am new to golang and looking for a cache library.
after read your blog, I write a small code for study cache set/get/expire. Now I have a issue, expire not working after timeout. still can get entry from bigcache. Did I missing something?

```go
package main

import (
	"fmt"
	"github.com/allegro/bigcache"
	"log"
	"time"
)

func main() {
	lifetime := 10 * time.Second

/*
	onRemove := func(key string, entry []byte) {
		log.Println(key)
	}
	config := bigcache.Config{
		// number of shards (must be a power of 2)
		Shards: 1024,
		// time after which entry can be evicted
		LifeWindow: lifetime,
		// rps * lifeWindow, used only in initial memory allocation
		MaxEntriesInWindow: 1000 * 10 * 60,
		// max entry size in bytes, used only in initial memory allocation
		MaxEntrySize: 500,
		// prints information about additional memory allocation
		Verbose: true,
		// cache will not allocate more memory than this limit, value in MB
		// if value is reached then the oldest entries can be overridden for the new ones
		// 0 value means no size limit
		HardMaxCacheSize: 8192,
		// callback fired when the oldest entry is removed because of its
		// expiration time or no space left for the new entry. Default value is nil which
		// means no callback and it prevents from unwrapping the oldest entry.
		OnRemove: onRemove,
	}

	cache, initErr := bigcache.NewBigCache(config)
*/
    cache, initErr := bigcache.NewBigCache(bigcache.DefaultConfig(10 * time.Second))
	if initErr != nil {
		log.Fatal(initErr)
	}

	cache.Set("my-unique-key", []byte("value"))

	if entry, err := cache.Get("my-unique-key"); err == nil {
		fmt.Println(string(entry))
	}

	timer := time.NewTimer(lifetime + time.Second)
	<-timer.C

	// Eviction is performed during writes to the cache since the lock is already acquired.
	cache.Set("key2", []byte("val2"))

	if entry2, err2 := cache.Get("my-unique-key"); err2 == nil {
		fmt.Println(string(entry2))
	} else {
		log.Println("not found")
	}
}
```

**Comment by janisz** [comment]
You got us :) We are really lazy and eviction is performed only when new item is inserted. If you try to obtain value from cache and it should be evicted but nothing was inserted you will get your value. 
Maybe we should improve documentation of [LifeWindow](https://github.com/allegro/bigcache/blob/master/config.go#L9) to make it clear that eviction could never happen.

**Comment by gangbanlau** [comment]
Yes ,I known your eviction design after reading your blog. So my testing code already call a cache set action after timeout. And then try to query timeouted entry.

// Eviction is performed during writes to the cache since the lock is already acquired.
cache.Set("key2", []byte("val2"))

**Comment by janisz** [comment]
You are correct. The problem is we only delete oldest entry from shard where we are going to insert new value. In your example you have 1024 shards and values get into different shards.

I've prepared test for this case: https://github.com/allegro/bigcache/pull/33

**Comment by flisky** [comment]
I'm trying to support expiration in #41, and PTAL.

**Comment by navinvictor** [comment]
> You got us :) We are really lazy and eviction is performed only when new item is inserted. If you try to obtain value from cache and it should be evicted but nothing was inserted you will get your value.
> Maybe we should improve documentation of [LifeWindow](https://github.com/allegro/bigcache/blob/master/config.go#L9) to make it clear that eviction could never happen.

Yes that would help others.
