### ISSUE TITLE
the different Expired judge in cacheShard.getWithInfo() and cacheShard.onEvict()

### ISSUE THREAD

**Issue by chen-zhuohan** [allegro/bigcache#318]
**What is the issue you are having?**

the different Expired judge in cacheShard.getWithInfo() and cacheShard.onEvict()

```go
// github.com/allegro/bigcache/v3@v3.0.2/shard.go
func (s *cacheShard) onEvict(oldestEntry []byte, currentTimestamp uint64, evict func(reason RemoveReason) error) bool {
	...
	if currentTimestamp-oldestTimestamp > s.lifeWindow { // here, is larger
		evict(Expired)
		return true
	}
	return false
}

func (s *cacheShard) getWithInfo(key string, hashedKey uint64) (entry []byte, resp Response, err error) {
        ...
	if currentTime-oldestTimeStamp >= s.lifeWindow { // here, is larger or equal
		resp.EntryStatus = Expired
	}
}
```

**What is BigCache doing that it shouldn't?**

They should have the same judge.

**Environment:**
- Version: github.com/allegro/bigcache/v3@v3.0.2/shard.go

**Comment by janisz** [comment]
Good catch! This inconsistency was introduced in https://github.com/allegro/bigcache/pull/168
I think we should have small helper method `isAlive` and use it instead of coping condition.

@chen-zhuohan   Would you like to contribute a patch?

```go
func isAlive() bool {
    return currentTimestamp-oldestTimestamp > s.lifeWindow
}```

**Comment by chen-zhuohan** [comment]
#319 here
