### ISSUE TITLE
BUG? concurrent set() waste memory

### ISSUE THREAD

**Issue by jinleileiking** [allegro/bigcache#332]
``` go 
for 0 - 10000 {
go func(){
cache.Set("1", "1")
}()
}
```
This will waste much mem. Is that correct?

**Comment by janisz** [comment]
It's correct. To prevent GC interaction we do not remove stale entries but overwrite them if configured memory limit is reached. If limit is set to 0 then memory could grow infinitely to OOM. To limit used memory use `HardMaxCacheSize`.
