### ISSUE TITLE
goruntine was blockde when get entry , sometime

### ISSUE THREAD

**Issue by tong3jie** [allegro/bigcache#335]
![image](https://user-images.githubusercontent.com/14191774/193298147-afde6fce-d8b5-4a28-aef0-e5c12d5e8e2b.png)
![image](https://user-images.githubusercontent.com/14191774/193298299-a2a854a9-9a4c-4720-a281-bb629e3b7333.png)

the numbers of goruntine was increasing by all the time

**Comment by janisz** [comment]
> the numbers of goruntine was increasing by all the time

That's weird an maybe unrealted to bigcache as it creates only one gorutine when cache is created 
https://github.com/allegro/bigcache/blob/c9426ba4b01ea37f412904df29a670711306e31e/bigcache.go#L91-L107

**Comment by tong3jie** [comment]
I think the goruntine blocked when I get a value and bigcache try to get a lock

**Comment by tong3jie** [comment]
yes,I think I get the blocked reason.
it about that I set a new vallue when the callback of remove was called.
