### ISSUE TITLE
Shutting down cleanup routine with ctx

### ISSUE THREAD

**Issue by alok87** [allegro/bigcache#336]
**What is the issue you are having?**
No issue, saw the NewBigCache() creates a go routine but does not take the context from the users and does not do a graceful shutdown of that go routine on context cancellation.
```go
// NewBigCache initialize new instance of BigCache
func NewBigCache(config Config) (*BigCache, error) {
	return newBigCache(config, &systemClock{})
}
```

**Expected**
```go
// NewBigCache initialize new instance of BigCache
func NewBigCache(ctx context.Context, config Config) (*BigCache, error) {
	return newBigCache(config, &systemClock{})
}

go func() {
			ticker := time.NewTicker(config.CleanWindow)
			defer ticker.Stop()
			for {
				select {
                                 case <-ctx.Done():
                                         fmt.Println("ctx done, shutting down")
                                         return
				case t := <-ticker.C:
					cache.cleanUp(uint64(t.Unix()))
				case <-cache.close:
					return
				}
			}
		}()
```

**Environment:**
- Version (git sha or release): v3.2.0
- OS (e.g. from `/etc/os-release` or winver.exe): macOS 
- go version: 1.19

**Comment by janisz** [comment]
@alok87 Good point. When bigcache was created there were no context in std lib. Now we should support that to prevent gorutine leakage. 

@alok87 Would you like to contribute a PR for this?

**Comment by alok87** [comment]
Sure, will give a PR
