### ISSUE TITLE
Bump go version

### ISSUE THREAD

**Issue by janisz** [allegro/bigcache#345]
Go 1.19 changes gofmt requirements. So in order to make bigcache build on 1.19 we need to fix formatting and upm go version in CI config.

**Comment by Ashish0z** [comment]
I can work on this issue

**Comment by 11-aryan** [comment]
I would like to work on this issue, could you please give me some more information so that I can get started with it?

**Comment by janisz** [comment]
It was done by:
- https://github.com/allegro/bigcache/pull/352
