### ISSUE TITLE
LifeWindow Not valid

### ISSUE THREAD

**Issue by dhffb** [allegro/bigcache#347]
```go
config := bigcache.Config{
		Shards:             1024,             
		LifeWindow:         3 * time.Second, 
		CleanWindow:        10 * time.Second, 
		MaxEntriesInWindow: 1000 * 10 * 60,   
		MaxEntrySize:       512,              
		Verbose:            false,            
		HardMaxCacheSize:   1024,            
		OnRemove:           nil,           
		OnRemoveWithReason: nil,            
	}
	cache, _ := bigcache.New(context.Background(), config)
	cache.Set("my-unique-key", []byte("value"))
	for {
		entry, _ := cache.Get("my-unique-key")
		fmt.Println(string(entry))
		time.Sleep(time.Second)
	}
```

13s before not getting value，Why not after 3s?

**Comment by janisz** [comment]
https://github.com/allegro/bigcache/blob/982ec3b09cacb9936b88dcfdaed329870065cf23/config.go#L9-L13

Are you sure it's 13s not 11s? We have two settings `LifeWindow` after entry can be deleted and `CleanWindow` that configures how often cleanup happens. In yours example after 10s entries older than 3s will be removed (marked as removed). You can use `GetWithInfo` to get information about stealness  of entry and decide what to do with it.
