### ISSUE TITLE
why did my key expired

### ISSUE THREAD

**Issue by gaozhenyusky** [allegro/bigcache#349]
**config**
```
var cache *bigcache.BigCache

func init() {
	config := bigcache.Config{
		Shards: 1024,
		LifeWindow: 1 * time.Hour,
		CleanWindow: 0,
		MaxEntriesInWindow: 1000 * 10 * 60,
		MaxEntrySize: 500,
		Verbose:      false,
		HardMaxCacheSize: 8192,
		OnRemoveWithReason: func(key string, entry []byte, reason bigcache.RemoveReason) {
			logger.Debugf("bigCache lost something, key:[%s], entry:[%s], reason:[%v]", key, string(entry), reason)
		},
		Logger: logger.GetLog(),
	}
	var err error
	cache, err = bigcache.NewBigCache(config)
	if err != nil {
		log.Fatalf("pCache init failed: %v \n", err)
	}
}
```

I use `CleanWindow=0`, it means always not expired?, but when i see the debug log, show like this
```
{"level":"debug","ts":"2022-11-22T19:06:38.606+0800","caller":"logger/std.go:29","msg":"bigCache lost something, key:[/platform_gateway_chonglou_rule/gw-object/clientAuth], entry:[\ufffd\ufffd\u0010\u0000\u001echonglou/model/rule.ClientAuth\ufffd\ufffd\u0003\u0001\u0001\nClientAuth\u0001\ufffd\ufffd\u0000\u0001\u0005\u0001\u0007Enabled\u0001\u0002\u0000\u0001\u000cAuthEndpoint\u0001\u000c\u0000\u0001\rRequestHeader\u0001\u000c\u0000\u0001\tTokenType\u0001\u000c\u0000\u0001\nAuthPrefix\u0001\u000c\u0000\u0000\u0000\u0004\ufffd\ufffd\u0001\u0000], reason:[1]"}
```

I just hope my cache never expired, how can i do? thx )

**Environment:**
- Version (git sha or release): v3@v3.0.2
- OS (e.g. from `/etc/os-release` or winver.exe): CentOS Linux 7 (Core)
- go version: 1.19

**Comment by gaozhenyusky** [comment]
Or in other words, Is there something wrong with my conf

**Comment by janisz** [comment]
Does it expire after 1 hour? If so then set `LifeWindow: 0` and that will prevent eviction.
https://github.com/allegro/bigcache/blob/0c7635518190a7d4053a104bb329b98837727eeb/config.go#L9

**Comment by gaozhenyusky** [comment]
> I double checked on this and it looks like in your case it wont work. 0 means everything will be imiedietally evicted so you need to use some bigger value.

wow, i update `LifeWindow: 10 * 365 * 24 * time.Hour` and try it again.
Actually in my project i just want use `bigCache` like Map now, Whether to add a property in `bigcache.Config` like `NeverLost` ?

**Comment by janisz** [comment]
It's complicated. In your configuration you have LifeWindow and HardMaxCacheSize. What bigcache should do if you need more memory than HardMaxCacheSize? Currently it will evict the oldest entry and replace it with new one. You can set `HardMaxCacheSize` to 0 to allow it growing infinitely but I don't recommend that :) 

https://github.com/allegro/bigcache/blob/982ec3b09cacb9936b88dcfdaed329870065cf23/config.go#L25-L32

**Comment by gaozhenyusky** [comment]
thx, u r right  :)
