### ISSUE TITLE
No way to increment value without updating the timestamp

### ISSUE THREAD

**Issue by vic4hub** [allegro/bigcache#35]
These commonly used methods are missing:

1) Increment/Decrement integer-based value without forcing a set, which puts a new timestamp - this is a problem in that, when I need to collect counts for keys which are popular, they may never expire (lets say expiration/eviction triggers a callback function which writes count value every "5 minutes" to log file)

2) Delete key - there is not way to remove a key or force eviction function on particular keys, overwriting assumes one has a new value

Nice to have: When calling "Reset" would be nice to trigger OnRemove callback or to provide another function which does that

**Comment by janisz** [comment]
1. If you need map of integers then bigcache is overkill. You won't gain any performance improvements comparing to concurrent-map becouse map int to int won't be scanned by GC. 

2. Indeed `Delete` is missing. I don't remember why we skipped it. You can emulate it with special value e.g., replace with empty bytes. 

3. I concurr. I think there should be dedicated function `Clean` that will lock cache and iterate over values calling eviction callback and finally reset.

**Comment by vic4hub** [comment]
First off, thank you very much for sharing this code, it is quite useful, as for item 1. Agreed, however in my case I wold use it as general purpose cache.
