### ISSUE TITLE
Add memory allocation hard limit

### ISSUE THREAD

**Issue by adamdubiel** [allegro/bigcache#4]
I would like to have a hard limit for max cache size, so for example my application won't be killed by OOMKiller, losing all cache data.

**Comment by Freeaqingme** [comment]
It would be really awesome if this could be implemented. Right now that's the only reason I'm not using bigcache, yet. I implemented myself something similar by simply atomically updating a uint field 'size' with every addition or deletion containing the total number of bytes contained in my map ( https://github.com/Freeaqingme/ClueGetter/blob/develop/src/cluegetter/messagePersist.go#L499 ).

I'm not sure how something similar would fit in the bigcache architecture though.

**Comment by druminski** [comment]
Hi, if this blocks you from using bigcache then it definitely receives higher priority on my list :)
I will implement it in the coming days.

**Comment by druminski** [comment]
@Freeaqingme please take a look at #10 PR and verify if you can now use bigcache. If it is ok then I will merge it.

**Comment by druminski** [comment]
Implemented & merged, closing the issue.
