### ISSUE TITLE
Update release notes for v1.0.0

### ISSUE THREAD

**Issue by mxplusb** [allegro/bigcache#52]
The release notes for v1.0.0 won't help new users. Below is a template which can help.

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

---

**Implemented enhancements:**

- Feature Request: support to clean expired entries [\#41](https://github.com/allegro/bigcache/pull/41) ([flisky](https://github.com/flisky))
- Improve fnv64a hashing algorithm by remove all allocations [\#19](https://github.com/allegro/bigcache/pull/19) ([mateuszdyminski](https://github.com/mateuszdyminski))

**Fixed bugs:**

- Hard max cache size exceeded [\#18](https://github.com/allegro/bigcache/issues/18)
- Entries indexes stay unchanged after additional memory allocation [\#8](https://github.com/allegro/bigcache/pull/8) ([druminski](https://github.com/druminski))

**Closed issues:**

- Item is not getting updated [\#39](https://github.com/allegro/bigcache/issues/39)
- Eviction not perform after timeout [\#31](https://github.com/allegro/bigcache/issues/31)
- Old entries \(un-updated\) values stored in the byte queue [\#30](https://github.com/allegro/bigcache/issues/30)
- Push emptyBlobLen inside the allocateAdditionalMemory\(\) function [\#29](https://github.com/allegro/bigcache/issues/29)
- ARC cache ? [\#28](https://github.com/allegro/bigcache/issues/28)
- Redis [\#27](https://github.com/allegro/bigcache/issues/27)
- Clear Cache [\#23](https://github.com/allegro/bigcache/issues/23)
- What is the purpose of "entries     queue.BytesQueue" [\#21](https://github.com/allegro/bigcache/issues/21)
- Event handlers for evict? [\#14](https://github.com/allegro/bigcache/issues/14)
- Add per entry expiration [\#13](https://github.com/allegro/bigcache/issues/13)
- Add memory allocation hard limit [\#4](https://github.com/allegro/bigcache/issues/4)

**Merged pull requests:**

- Get rid of defer in interator [\#48](https://github.com/allegro/bigcache/pull/48) ([cristaloleg](https://github.com/cristaloleg))
- Extract Lock/Unlock from shard [\#47](https://github.com/allegro/bigcache/pull/47) ([cristaloleg](https://github.com/cristaloleg))
- travis: add 1.x instead 1.9 to go versions [\#45](https://github.com/allegro/bigcache/pull/45) ([dvrkps](https://github.com/dvrkps))
- Use RLock/RUnlock for read shard.Len [\#44](https://github.com/allegro/bigcache/pull/44) ([cristaloleg](https://github.com/cristaloleg))
- Update go to 1.9 [\#43](https://github.com/allegro/bigcache/pull/43) ([janisz](https://github.com/janisz))
- tests: keyify Config [\#42](https://github.com/allegro/bigcache/pull/42) ([flisky](https://github.com/flisky))
- Changed locking strategy [\#37](https://github.com/allegro/bigcache/pull/37) ([mxplusb](https://github.com/mxplusb))
- Comparsion -\> comparison [\#34](https://github.com/allegro/bigcache/pull/34) ([rafax](https://github.com/rafax))
- Add test for timing eviction for multiple shards [\#33](https://github.com/allegro/bigcache/pull/33) ([janisz](https://github.com/janisz))
- Build on go 1.8 [\#32](https://github.com/allegro/bigcache/pull/32) ([wendigo](https://github.com/wendigo))
- Compile on golang's tip [\#26](https://github.com/allegro/bigcache/pull/26) ([wendigo](https://github.com/wendigo))
- Add Reset\(\) to cache [\#25](https://github.com/allegro/bigcache/pull/25) ([wendigo](https://github.com/wendigo))
- Zero alloc byte to string conversion [\#24](https://github.com/allegro/bigcache/pull/24) ([wendigo](https://github.com/wendigo))
- Add Iterator to iterate over keys [\#22](https://github.com/allegro/bigcache/pull/22) ([wendigo](https://github.com/wendigo))
- Use golang 1.7 subtests [\#20](https://github.com/allegro/bigcache/pull/20) ([wendigo](https://github.com/wendigo))
- Build only for go 1.6 [\#17](https://github.com/allegro/bigcache/pull/17) ([janisz](https://github.com/janisz))
- Adding info about OnRemove callback to readme.md [\#16](https://github.com/allegro/bigcache/pull/16) ([druminski](https://github.com/druminski))
- resolves \#14 | Adding OnRemove handler [\#15](https://github.com/allegro/bigcache/pull/15) ([druminski](https://github.com/druminski))
- Add some tests [\#11](https://github.com/allegro/bigcache/pull/11) ([janisz](https://github.com/janisz))
- Implementing hard max cache size [\#10](https://github.com/allegro/bigcache/pull/10) ([druminski](https://github.com/druminski))
- Typo fix [\#9](https://github.com/allegro/bigcache/pull/9) ([synweap15](https://github.com/synweap15))
- Wrap entry optimization [\#7](https://github.com/allegro/bigcache/pull/7) ([druminski](https://github.com/druminski))
- Add linter in travis [\#6](https://github.com/allegro/bigcache/pull/6) ([janisz](https://github.com/janisz))
- Little optimizations [\#5](https://github.com/allegro/bigcache/pull/5) ([wendigo](https://github.com/wendigo))
- Performance comparison with freecache and map [\#3](https://github.com/allegro/bigcache/pull/3) ([druminski](https://github.com/druminski))
- Handling values bigger than whole slice in bytes queue [\#2](https://github.com/allegro/bigcache/pull/2) ([druminski](https://github.com/druminski))

**Comment by janisz** [comment]
@mxplusb Thanks for pointing it out. I've just updated our release https://github.com/allegro/bigcache/releases/tag/v1.0.0
