### ISSUE TITLE
GC Pause time for maps.

### ISSUE THREAD

**Issue by irfn** [allegro/bigcache#59]
I understand that benchmarks will depend on the machine used.
Following is from a 2017 Macbook pro (2.8 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3)

However native Maps seems to have had a massive improvement. Is this due to go 1.9?

`go version go1.9.2 darwin/amd64`

```
go run caches_gc_overhead_comparison.go
Number of entries:  20000000
GC pause for bigcache:  45.222µs
GC pause for freecache:  37.043µs
GC pause for map:  59.572µs
```

**Comment by janisz** [comment]
@irfn Looks interesting. We might need to do more benchmarks (best if we find what change fixes GC map issues in go). Maybe bigcache is no longer needed and we can rely on map from stdlib. That would be great!

**Comment by cristaloleg** [comment]
Looks like bench inaccuracy due to different load in CPU(background processes etc).
Numbers are quite small(it's microseconds!) so any small fluctuations might cause quite different results.
I don't think bigcache isn't needed anymore, we might have bigger GC pauses, but during concurrent read/write shards will save us and lower our latency.
Here are my results.
Go:
```
go version
go version go1.9.2 darwin/amd64
```
Bench:
```
go run caches_gc_overhead_comparison.go
Number of entries:  20000000
GC pause for bigcache:  36.712µs
GC pause for freecache:  59.594µs
GC pause for map:  62.094µs
```
Machine:
```
MacBook Pro (15-inch, 2017)
2,9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
```

**Comment by irfn** [comment]
@cristaloleg I have similar results on same machine.

I am suggesting an improvement to the benchmark to get better visibility for go 1.9
There are some changes in go GC mentioned here wrt GC pauses. https://golang.org/doc/go1.9#gc

Mentioned: "The runtime.ReadMemStats function now takes less than 100µs even for very large heaps"
Few other things that point to fact that GC comparison would need to be checked again. @cristaloleg Like you mentioned the perf bottleneck may appear at higher amount of data / ops etc.

**Comment by cristaloleg** [comment]
Yeah, GC isn't a problem anymore 😄

**Comment by mxplusb** [comment]
> Maybe bigcache is no longer needed and we can rely on map from stdlib. That would be great!

Even if maps do end up with massive improvements, I hope bigcache stays around! It's still better than the alternatives, in my mind, haha.

**Comment by buraksezer** [comment]
Built-in map still looks like a problem for GC performance. Please take a look at the following posts: 

https://www.komu.engineer/blogs/go-gc-maps
https://syslog.ravelin.com/gc-is-bad-and-you-should-feel-bad-e9bdd9324f0
https://www.reddit.com/r/golang/comments/7sws11/benchmarking_gc_pause_times_with_string_and_int/

I have tried the case which described in the first post on my computer with Go 1.10 and the result is the same. What do you think?

**Comment by mxplusb** [comment]
Bigcache is an exceedingly optimised version of the built-in map type that works around the garbage collection subsystem by using a (FNV-1a Hash Algorithm)[https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function] which converts our interface types into raw uint64s so we can store them in a standard map without pointers. By doing that, we are completely avoiding the GC. This is a great opportunity for a case study on this optimisation.

**Comment by buraksezer** [comment]
I tried to state that go1.10 has the same problem:  
```
$ for t in 1 2; do go run gc.go $t; done
With a map of strings, GC took: 2.442295076s
With map of strings(that are hashed to ints), GC took:: 23.268634ms

$ go version
go version go1.10 darwin/amd64
```

**Comment by mxplusb** [comment]
@buraksezer gotcha! Sorry, missed some of the context. I reran the stats comparison with go1.10 windows/amd64 for #69 and fixed a GC bug if you want to see the updated comparisons.
