### ISSUE TITLE
LifeWindow not work!

### ISSUE THREAD

**Issue by reza3vi** [allegro/bigcache#63]
LifeWindow  property not work, entry not remove after LifeWindow .

**Comment by janisz** [comment]
@reza3vi Thank you for this issue. Can you give us more details? Best if you can provide an example reproducing this bug.

**Comment by reza3vi** [comment]
c := bigcache.Config{
		Shards:             1024,
		LifeWindow:         10 * time.Minute,
		MaxEntriesInWindow: 1000 * 10 * 60,
		MaxEntrySize:       500,
		Verbose:            true,
		HardMaxCacheSize:   8192,
	}
        db, _ := bigcache.NewBigCache(c)

**Comment by janisz** [comment]
If you are referring to the situation when an object is available after `LifeWindow` period it's the desired behaviour. There is event test for it https://github.com/allegro/bigcache/blob/master/bigcache_test.go#L96 and documentation states 

> [time after which entry **can** be evicted](https://github.com/allegro/bigcache/blob/v1.0.0/config.go#L9)

so there is no guarantee that entry will be evicted if nothing was updated.

**Comment by reza3vi** [comment]
cache, _ := bigcache.NewBigCache(bigcache.DefaultConfig(5 * time.Second))
        cache.Set("key1", []byte("a"))
        time.Sleep(10 * time.Second)
        cache.Set("key2", []byte("b"))
        b, _ := cache.Get("key1")
        println(string(b))
        
        // print --> a

**Comment by reza3vi** [comment]
Should remove key1 after 5 sec. But not work

**Comment by reza3vi** [comment]
Set CleanWindow: time.Minute

Work!

**Comment by janisz** [comment]
Cool :sunglasses: I'm closing the issue.
