### ISSUE TITLE
Document what happens when an entry is not in the cache

### ISSUE THREAD

**Issue by stevenroose** [allegro/bigcache#66]
Does it return `nil, nil` or an error?

**Comment by janisz** [comment]
It returns an error. See: https://github.com/allegro/bigcache/blob/master/bigcache_test.go#L56

**Comment by stevenroose** [comment]
@janisz Was documentation added? This issue was created to ensure adequate documentation was provided in the API docs (method comment).

**Comment by janisz** [comment]
My bad. Thank you for the contribution!
