### ISSUE TITLE
Collaborator Permissions?

### ISSUE THREAD

**Issue by mxplusb** [allegro/bigcache#70]
I would like to request access to the project as a collaborator. I've contributed the server implementation (making me the second largest contributor), increased performance by 20% for parallel sets by fixing the locking strategy, and maintained contribution activity through comments in various issues and PRs.

Having collaborator access would allow me to work in branches in the main project as well as merge requests from the community so long as they meet the project standards. My goal is to get earlier feedback on useful features from various branches I think would be good (mostly for the web server) and maintain a higher level of commitment to the project.

I promise I won't `git push -f master`. 😄

**Comment by mxplusb** [comment]
I mentioned this in a private email, but I will also be willing to sign a Contributor's License Agreement, if that is a requirement.

**Comment by adamdubiel** [comment]
Mike, it's great to hear that you would like to commit to development of bigcache by becoming a collaborator. We value your work and effort and @janisz had no doubts that you should become one.

So i added you as a collaborator to this project :) Welcome on board! 🍾 🎉

For know we do not require CLA, but it will probably change in the future. When it does I will reach out.

**Comment by mxplusb** [comment]
That's awesome! I'm really looking forward to helping drive continued success for this product!
