### ISSUE TITLE
Per Item TTL

### ISSUE THREAD

**Issue by hobbs** [allegro/bigcache#81]
Any thoughts on having a per item TTL similar to memcache/freecache/redis/etc? Unless I missed something, it appears that's not possible right now.

I think it'd be fairly easy to implement (and I can send PR if I do). Just wanted to start the discussion.

**Comment by hobbs** [comment]
From: https://redis.io/commands/expire#how-redis-expires-keys

> Specifically this is what Redis does 10 times per second:
> 
> -    Test 20 random keys from the set of keys with an associated expire.
> -    Delete all the keys found expired.
> -    If more than 25% of keys were expired, start again from step 1.
> 
> This is a trivial probabilistic algorithm, basically the assumption is that our sample is representative of the whole key space, and we continue to expire until the percentage of keys that are likely to be expired is under 25%

**Comment by mxplusb** [comment]
@hobbs I don't see why not, but that would definitely change the API surface. Would you be willing to send in a WIP PR so we can take a look? I'd be curious to see what your implementation looks like.

**Comment by hobbs** [comment]
Ended up just doing lazy TTL enforcement in the package that is using the cache, so no PR for now.
