### ISSUE TITLE
Goroutine leak in NewBigCache

### ISSUE THREAD

**Issue by enocom** [allegro/bigcache#82]
An invocation of `bigcache.NewBigCache` starts a goroutine to [handle cache cleanup](https://github.com/allegro/bigcache/blob/master/bigcache.go#L76-L82) before returning a reference to `cache` to the caller.

Once the returned reference `cache` goes out of scope in the caller's code, though, the garbage collector will be unable to collect it, as the cache cleanup goroutine will continue to run and therefore will be leaked.

To fix this problem, the `BigCache` type should probably have a `Close` function to stop its helper goroutine.

/cc @mxplusb

**Comment by mxplusb** [comment]
Thanks @enocom for pointing this out. Ideally I'd like to do this outside the scope of a user's purview, but I guess we'll see what happens.

**Comment by jasonkeene** [comment]
Implementing `io.Closer` is a pretty common pattern in Go for cleaning up goroutines. I'm not aware of any way to accomplish this outside the user's purview. Go is really explicit about having the user handle these things.
