### ISSUE TITLE
Feedback from Community Talk

### ISSUE THREAD

**Issue by mxplusb** [allegro/bigcache#83]
I totally forgot to capture this feedback live, and that's something I regret doing, so I will try to capture this well. I'm tagging the people I can remember being there, so if you see someone from the meetup is missing and you want to make sure their feedback is captured, please add them!

[Here](https://pivotal.zoom.us/recording/play/v7ijVuoFILrBPsSSqPH9ZM000f8k-3QpAZ0gRgn-LGH4_l3nOGz8Uq3Lqiwki3Q2) is the talk. The audio is sketchy for some reason, but next time I give this talk, I can make sure it's better.

* Everyone loved the performance focus!
* What are the use cases?
* Does the cache persist past program execution? i.e., can you restart the cache and have it rebuild itself
* Is there an option to distribute the cache? i.e., cache clustering
* How do we handle eviction?
* Is the cache thread safe?
* What is the performance like with billions of objects/hundreds of GBs?

Would love to really involve the community on this one!

//cc @enocom @jasonkeene @kcboyle

**Comment by mfrw** [comment]
Would it be possible to make the talk accessible to all?

**Comment by mxplusb** [comment]
I didn't realise it was auth locked, here is a Youtube version: https://youtu.be/K15B1FYkLDg. The audio is still sketchy because of the recording equipment.

**Comment by mxplusb** [comment]
Closing since any feedback has been long captured.
