### ISSUE TITLE
Dependent cache items

### ISSUE THREAD

**Issue by roker** [allegro/bigcache#87]
This is one feature I found missing in all type of caches. The cached items cant be atomically made dependant to one another, the simple case would be paging:

GET /somepage/paging-1 --> cache.set("/something/paging-1", content)
GET /somepage/paging-2 --> cache.set("/something/paging-2", content)
GET /somepage/paging-3 --> cache.set("/something/paging-3", content)
POST /somepage --> cache.invalidate("/something/paging-*)

The iterator can be used, but if a lot of entries are cached, it really isnt efficient. Some additional logic would be fine, to specify that "/something/paging-1" is dependant to "/something/" and invalidates/calls hook if "/something/" has changed. It is not an issue to implement a map but since it has to be atomic to avoid race conditions (one client invalidates cache, the second is requesting it), it would be really nice if it would be implemented on bigcache level to automatically create a hierarchy where changing one item invalidates all dependent items.

**Comment by mxplusb** [comment]
I would recommend storing that information outside of the cache as that's a bit outside the scope of what we're trying to achieve at this stage. I do think it's interesting, but we're not there now. :)
