### ISSUE TITLE
Expose ByteQueue capacity from Cache methods

### ISSUE THREAD

**Issue by wI2L** [allegro/bigcache#88]
The cache already exposes the number of entries in the cache through `Len()` and some additional useful statistics through `Stats()`. I would like to be able to get the underlying size in bytes of the cache, either from a method or as a new field of the `Stats` type.

The `ByteQueue` package already have a `Capacity()` methods that returns exactly the information I need. Could we somehow, using one of the two techniques before, expose the size of the cache ?

Thanks

**Comment by cristaloleg** [comment]
@wI2L thanks for the suggestion 😉
