### ISSUE TITLE
Using bigcache with google appengine

### ISSUE THREAD

**Issue by ahmadissa** [allegro/bigcache#96]
I'm trying to use bigcache with google appengine (go1.9) however I got the below error

`go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/allegro/bigcache/bigcache.go from GOPATH
`

After trying some options I was able to solve the problem by not using the "unsafe" package in "encoding.go/bytesToString"

The original function was 

```
func bytesToString(b []byte) string {
	bytesHeader := (*reflect.SliceHeader)(unsafe.Pointer(&b))
	strHeader := reflect.StringHeader{Data: bytesHeader.Data, Len: bytesHeader.Len}
	return *(*string)(unsafe.Pointer(&strHeader))
}
```

I have changed it to:

```
func bytesToString(b []byte) string {
	return string(b)
}
```

My question is:

Is it ok doing this change? Do you think I will face any issues?

Thanks

**Comment by cristaloleg** [comment]
Hi, thanks for reaching out.

Yes, your change is totally safe(there is no `unsafe` package in it 😂 ) and the logic of the code is the same.

Probably we should add a build tag for `appengine` to make life easier for bigcache users.
